# Generated by Django 4.1.1 on 2022-09-20 06:22

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('state_name', models.CharField(blank=True, max_length=50)),
                ('district_name', models.CharField(blank=True, max_length=50)),
                ('village_name', models.CharField(blank=True, max_length=50)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, unique=True)),
                ('text_column_1', models.TextField(blank=True)),
                ('text_column_2', models.TextField(blank=True)),
                ('text_column_3', models.TextField(blank=True)),
                ('text_column_4', models.TextField(blank=True)),
            ],
        ),
    ]
