# Generated by Django 4.1.1 on 2022-09-21 03:48

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('CoreApp', '0003_alter_farmerinfo_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerinfo',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
        migrations.CreateModel(
            name='FarmerInfoTelugu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('state_name', models.CharField(max_length=50, null=True)),
                ('district_name', models.CharField(max_length=50, null=True)),
                ('village_name', models.CharField(max_length=50, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('text_column_1', models.TextField(null=True)),
                ('text_column_2', models.TextField(null=True)),
                ('text_column_3', models.TextField(null=True)),
                ('text_column_4', models.TextField(null=True)),
                ('farmer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CoreApp.farmerinfo')),
            ],
        ),
        migrations.CreateModel(
            name='FarmerInfoPunjabi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('state_name', models.CharField(max_length=50, null=True)),
                ('district_name', models.CharField(max_length=50, null=True)),
                ('village_name', models.CharField(max_length=50, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('text_column_1', models.TextField(null=True)),
                ('text_column_2', models.TextField(null=True)),
                ('text_column_3', models.TextField(null=True)),
                ('text_column_4', models.TextField(null=True)),
                ('farmer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CoreApp.farmerinfo')),
            ],
        ),
        migrations.CreateModel(
            name='FarmerInfoMarathi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('state_name', models.CharField(max_length=50, null=True)),
                ('district_name', models.CharField(max_length=50, null=True)),
                ('village_name', models.CharField(max_length=50, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('text_column_1', models.TextField(null=True)),
                ('text_column_2', models.TextField(null=True)),
                ('text_column_3', models.TextField(null=True)),
                ('text_column_4', models.TextField(null=True)),
                ('farmer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CoreApp.farmerinfo')),
            ],
        ),
        migrations.CreateModel(
            name='FarmerInfoHindi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('state_name', models.CharField(max_length=50, null=True)),
                ('district_name', models.CharField(max_length=50, null=True)),
                ('village_name', models.CharField(max_length=50, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('text_column_1', models.TextField(null=True)),
                ('text_column_2', models.TextField(null=True)),
                ('text_column_3', models.TextField(null=True)),
                ('text_column_4', models.TextField(null=True)),
                ('farmer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CoreApp.farmerinfo')),
            ],
        ),
    ]
