# Generated by Django 4.1.1 on 2022-09-21 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreApp', '0004_alter_farmerinfo_phone_farmerinfotelugu_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmerinfohindi',
            name='id',
        ),
        migrations.RemoveField(
            model_name='farmerinfomarathi',
            name='id',
        ),
        migrations.RemoveField(
            model_name='farmerinfopunjabi',
            name='id',
        ),
        migrations.RemoveField(
            model_name='farmerinfotelugu',
            name='id',
        ),
        migrations.AlterField(
            model_name='farmerinfohindi',
            name='farmer_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='farmerinfomarathi',
            name='farmer_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='farmerinfopunjabi',
            name='farmer_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='farmerinfotelugu',
            name='farmer_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
