# Generated by Django 4.1.1 on 2022-09-21 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreApp', '0005_remove_farmerinfohindi_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerinfo',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
